- id: '1691712571143'
  alias: Send a notification when internet speeds are low
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 9e3cf823320a365ecfe5179c057f3fa5
    entity_id: c0c6838cb9c77437e09e6da2f2cae91d
    domain: sensor
    below: 100
  - type: value
    platform: device
    device_id: 9e3cf823320a365ecfe5179c057f3fa5
    entity_id: d4541f2be787dd28dd145186c1996ba9
    domain: sensor
    below: 10
  condition: []
  action:
  - device_id: cbb12a2c31fd10894350f2bc201ef429
    domain: mobile_app
    type: notify
    message: The{% set download_state = states('sensor.speedtest_download')%}{% set
      upload_state = states('sensor.speedtest_upload') %}{% if is_number(download_state)
      and download_state | float < 25 %} download speed for the last speed test was
      {{download_state}}Mbps. {% else %} upload speed for the last speed test was
      {{upload_state}}Mbps.  {% endif %}
    title: Slow Internet Speed
  mode: single
- id: '1691712766126'
  alias: Turn off Humidifier if >35%
  description: ''
  trigger:
  - type: humidity
    platform: device
    device_id: 1affbb39843799ce8a8e31386f0d2fa3
    entity_id: sensor.bedroom_motion_sensor_humidity
    domain: sensor
    above: 40
  condition: []
  action:
  - type: turn_off
    device_id: 057733e55a8a9036001f07ad0ee4f7fd
    entity_id: switch.humidifier_plug_2
    domain: switch
  mode: single
- id: '1691712783271'
  alias: Turn on humidifier if <35%
  description: ''
  trigger:
  - type: humidity
    platform: device
    device_id: 1affbb39843799ce8a8e31386f0d2fa3
    entity_id: sensor.bedroom_motion_sensor_humidity
    domain: sensor
    below: 40
  condition: []
  action:
  - type: turn_on
    device_id: 057733e55a8a9036001f07ad0ee4f7fd
    entity_id: switch.humidifier_plug_2
    domain: switch
  mode: single
- id: '1691712802022'
  alias: Default Bedroom Setup [Manual Trigger]
  description: ''
  trigger: []
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.bedroom_lights
    metadata: {}
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.bedroom_motion_sensor_state
  - service: lifx.effect_stop
    data: {}
    target:
      area_id: master_bedroom
  mode: restart
- id: '1691712880929'
  alias: Pico Remote In-Wall
  description: ''
  use_blueprint:
    path: stephack/core-pico.yaml
    input:
      auto_mode: restart
      bottom_off:
      - service: light.turn_off
        data: {}
        target:
          area_id:
          - master_bedroom
          - master_bathroom
          - closet
      - type: turn_off
        device_id: 2c5ebf3c191e5b31022d7be2ed1b03f2
        entity_id: switch.hue_motion_sensor_1_motion
        domain: switch
      - delay:
          hours: 1
          minutes: 0
          seconds: 0
          milliseconds: 0
      - type: turn_on
        device_id: 2c5ebf3c191e5b31022d7be2ed1b03f2
        entity_id: switch.hue_motion_sensor_1_motion
        domain: switch
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.bedroom_motion_sensor_state
      top_on:
      - service: scene.turn_on
        target:
          entity_id: scene.bedroom_lights
        metadata: {}
      - type: turn_on
        device_id: 2c5ebf3c191e5b31022d7be2ed1b03f2
        entity_id: switch.hue_motion_sensor_1_motion
        domain: switch
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.bedroom_motion_sensor_state
      pico_remote: 10efdd0ec4f1be2841b5382409d4cb14
      mode_max: 8
      middle_stop:
      - service: scene.turn_on
        target:
          entity_id: scene.master_bedroom_reading
        metadata: {}
      - delay:
          hours: 1
          minutes: 0
          seconds: 0
          milliseconds: 0
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.bedroom_motion_sensor_state
      down_lower:
      - service: media_player.volume_down
        data: {}
        target:
          entity_id: media_player.bedroom_sonos
      middle_stop_release:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.bedroom_motion_sensor_state
      up_raise:
      - service: media_player.volume_up
        data: {}
        target:
          entity_id: media_player.bedroom_sonos
      bottom_off_release: []
      up_raise_release: []
- id: '1691712964071'
  alias: Pico Remote Bed Frame
  description: ''
  use_blueprint:
    path: stephack/core-pico.yaml
    input:
      auto_mode: restart
      bottom_off:
      - service: light.turn_off
        data: {}
        target:
          area_id:
          - master_bedroom
          - master_bathroom
          - closet
      - delay:
          hours: 1
          minutes: 0
          seconds: 0
          milliseconds: 0
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.bedroom_motion_sensor_state
      top_on:
      - service: scene.turn_on
        target:
          entity_id: scene.bedroom_lights
        metadata: {}
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.bedroom_motion_sensor_state
      pico_remote: d33322b65c2f71efd842ebfee2272dc4
      mode_max: 8
      middle_stop:
      - service: scene.turn_on
        target:
          entity_id: scene.master_bedroom_reading
        metadata: {}
      - delay:
          hours: 1
          minutes: 0
          seconds: 0
          milliseconds: 0
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.bedroom_motion_sensor_state
      down_raise:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.is_pico_down_held
      - repeat:
          while:
          - condition: state
            entity_id: input_boolean.is_pico_down_held
            state: 'on'
          sequence:
          - service: media_player.volume_down
            data: {}
            target:
              entity_id: media_player.bedroom_sonos
      down_lower:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.is_pico_down_held
      - repeat:
          while:
          - condition: state
            entity_id: input_boolean.is_pico_down_held
            state: 'on'
          sequence:
          - service: media_player.volume_down
            data: {}
            target:
              entity_id: media_player.bedroom_sonos
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 150
      middle_stop_release:
      - service: media_player.shuffle_set
        data:
          shuffle: true
        target:
          entity_id: media_player.bedroom_sonos
      - service: media_player.play_media
        data:
          media_content_type: playlist
          enqueue: replace
          media_content_id: https://open.spotify.com/playlist/5FmmxErJczcrEwIFGIviYo?si=c0716743e2314117
        target:
          entity_id: media_player.bedroom_sonos
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.bedroom_motion_sensor_state
      up_raise:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.is_pico_up_held
      - repeat:
          while:
          - condition: state
            entity_id: input_boolean.is_pico_up_held
            state: 'on'
          sequence:
          - service: media_player.volume_up
            data: {}
            target:
              entity_id: media_player.bedroom_sonos
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 150
      up_lower:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.is_pico_up_held
      bottom_off_release:
      - service: media_player.media_pause
        data: {}
        target:
          device_id: 62b4389f3b5b909f36ce07fe53905f01
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.bedroom_motion_sensor_state
      - delay:
          hours: 1
          minutes: 0
          seconds: 0
          milliseconds: 0
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.bedroom_motion_sensor_state
      up_raise_release:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.is_pico_up_held
      down_lower_release:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.is_pico_down_held
- id: '1691713834866'
  alias: Motion Sensing Master Bathroom Lights
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 3739f694a0054133a3b5a94c62b48016
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone
    domain: binary_sensor
  condition:
  - condition: or
    conditions:
    - condition: time
      after: 07:30:00
      before: '23:30:00'
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: time
      after: 09:00:00
      before: '23:30:00'
      weekday:
      - sat
      - sun
  action:
  - type: turn_on
    device_id: 7c6329880ab1433cca04846f548362e2
    entity_id: 44c2df0875c99ab1ce626a885fdbd786
    domain: switch
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 7c6329880ab1433cca04846f548362e2
    entity_id: 44c2df0875c99ab1ce626a885fdbd786
    domain: switch
  mode: restart
- id: '1691714153040'
  alias: Motion Sensing Master Bedroom Lights
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 9a75ed459178d9f05f7b9e5dfcc80f9a
    entity_id: e455c1c102679d727f5d5fc276731564
    domain: binary_sensor
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.bedroom_motion_sensor_state
      state: 'on'
    - condition: or
      conditions:
      - condition: time
        before: '23:00:00'
        after: 07:45:00
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      - condition: time
        before: '23:30:00'
        after: '10:00:00'
        weekday:
        - sat
        - sun
    - condition: or
      conditions:
      - condition: device
        type: is_off
        device_id: 8e5b5d5ca53c2f2527f5e18988bd2487
        entity_id: light.bed_frame
        domain: light
      - condition: device
        type: is_off
        device_id: 4bbcbe58ef5ba2acce372f9492da287d
        entity_id: light.desk_lightstrip
        domain: light
      - condition: device
        type: is_off
        device_id: b12cc8903d4c5327c3b2be37f7a2e912
        entity_id: light.computer_shelf
        domain: light
      - condition: device
        type: is_off
        device_id: 7d3da82cc61061af25542b16321d89a3
        entity_id: light.record_shelf
        domain: light
      - condition: device
        type: is_off
        device_id: 52f153663ddaca7d191c07f58526aee6
        entity_id: e8a3258910734dc66dbc88942144234b
        domain: light
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.bedroom_lights
    metadata: {}
  - service: adaptive_lighting.apply
    data:
      lights:
      - light.bed_frame
      - light.computer_shelf
      - light.desk_lightstrip
      - light.record_shelf
      adapt_color: true
      prefer_rgb_color: true
      turn_on_lights: true
      adapt_brightness: true
  - if:
    - type: is_no_motion
      condition: device
      device_id: aea80c457d793f16da9836a98e4e9cc7
      entity_id: bc373e13e264a70b02d75014b0dd0210
      domain: binary_sensor
      for:
        hours: 1
        minutes: 0
        seconds: 0
    then:
    - service: scene.turn_on
      target:
        entity_id: scene.new_scene
      metadata: {}
  mode: restart
- id: '1691714478126'
  alias: Turn lights off when I leave
  description: ''
  trigger:
  - platform: device
    device_id: 5ed4cc4b65ea1e76aea4bfbb88f98cd6
    domain: device_tracker
    entity_id: d76835ff89503dbe69592e5b082362c3
    type: leaves
    zone: zone.home
  condition:
  - type: is_no_motion
    condition: device
    device_id: 2c5ebf3c191e5b31022d7be2ed1b03f2
    entity_id: 0ebab270c041abc879e4023b641da0e0
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id: master_bedroom
  mode: single
- id: '1691714527341'
  alias: Motion Sensing Master Closet Light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.hue_motion_sensor_1_motion
      light_target:
        area_id: closet
      no_motion_wait: 600
- id: '1691714549452'
  alias: Turn on laundry room light when door opens
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 59ef993e8b02fa4181eadbb94685e59c
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: cd36b04759f5f9459fca2c76e5ea4033
    entity_id: 76a03f457cd8ae899247efebd3a473da
    domain: switch
  mode: single
- id: '1691714662947'
  alias: Pico Remote Master Bathroom
  description: ''
  use_blueprint:
    path: stephack/core-pico.yaml
    input:
      pico_remote: ec8d265c284bed9b46e51f0e1d6b7a84
      middle_stop:
      - type: toggle
        device_id: 9a75ed459178d9f05f7b9e5dfcc80f9a
        entity_id: d3cec644b3740cd153c461a555d2a851
        domain: switch
      top_on:
      - type: turn_on
        device_id: 7c6329880ab1433cca04846f548362e2
        entity_id: 44c2df0875c99ab1ce626a885fdbd786
        domain: switch
      bottom_off:
      - type: turn_off
        device_id: 7c6329880ab1433cca04846f548362e2
        entity_id: 44c2df0875c99ab1ce626a885fdbd786
        domain: switch
- id: '1691714779499'
  alias: Turn Off Closet Light When Door Closes
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: e06021ed3c39f842c16d7d50aeb16583
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_2
    domain: binary_sensor
  condition: []
  action:
  - type: turn_off
    device_id: 2aaa628e163aa4ad07d6502f7c5ad9fe
    entity_id: light.closet_light
    domain: light
  mode: single
- id: '1691714965294'
  alias: Turn off laundry room light when door closes
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 59ef993e8b02fa4181eadbb94685e59c
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
    domain: binary_sensor
  condition: []
  action:
  - type: turn_off
    device_id: cd36b04759f5f9459fca2c76e5ea4033
    entity_id: 76a03f457cd8ae899247efebd3a473da
    domain: switch
  mode: single
- id: '1691715004162'
  alias: Auto Bathroom Fan With Humidity
  description: ''
  use_blueprint:
    path: celsian/humidity_mod.yaml
    input:
      humidity_sensor: sensor.master_shower_humidity_sensor_humidity
      reference_humidity_sensor: sensor.my_ecobee_current_humidity
      fan_switch: switch.master_bathroom_fan_motion_switch
      humidity_automation_boolean: input_boolean.manually_turned_on_bathroom_fan
      rising_threshold: '15'
      falling_threshold: '15'
      reference_humidity: '55'
- id: '1691715029066'
  alias: Manually turn on master bathroom fan
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 9a75ed459178d9f05f7b9e5dfcc80f9a
    entity_id: d3cec644b3740cd153c461a555d2a851
    domain: switch
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.manually_turned_on_bathroom_fan
  - type: turn_on
    device_id: 9a75ed459178d9f05f7b9e5dfcc80f9a
    entity_id: d3cec644b3740cd153c461a555d2a851
    domain: switch
  mode: single
- id: '1691715058812'
  alias: Manually turn off master bathroom fan
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 9a75ed459178d9f05f7b9e5dfcc80f9a
    entity_id: d3cec644b3740cd153c461a555d2a851
    domain: switch
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.manually_turned_on_bathroom_fan
  - type: turn_off
    device_id: 9a75ed459178d9f05f7b9e5dfcc80f9a
    entity_id: d3cec644b3740cd153c461a555d2a851
    domain: switch
  mode: single
